<?php

namespace Club\Account\EconomicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessRepository extends EntityRepository
{
}
